### ISSUE TITLE
Output image size?  

### ISSUE THREAD

**Issue by ghost** [Eiim/JAEG#2]
Hey there, just trying this out...is there a way to modify the code to allow a larger output image size / be able to store more data/the same data as the original input audio? 
Currently it seems the output image sizes are only a few kilobytes. 
Could the output image size be chosen ahead of generating the JPEG somehow?  

Cheers!

**Comment by Eiim** [comment]
It would be possible to create an encoding scheme where other data is included, but what would that extra data be? And, I suppose, why would you want to do so in the first place? Although there's not much reason for this project at all, so perhaps that's a moot point.

**Comment by Eiim** [comment]
The reason for that is because WAV is entirely uncompressed, but sound data is highly compressible, so even a bad compression algorithm, like lossless JPEG (or at least near-lossless, I don't remember if max quality is actually 100% or not) will perform much better than no compression at all.

**Comment by Eiim** [comment]
I also don't remember the exact details of how the encoding works. It could be that there's some quantization going on when converting to JPEG such that you'll only ever get 8-bit audio out, even if you have higher-resolution input. That's something that could be improved by utilizing the color channels. I believe it also assumes a particular sample rate (44100 kHz, perhaps?) when converting back to audio, although when converting to JPEG it ignores sample rate, as each pixel is one sample, regardless of sample rate.

**Comment by MetrosiderosExcelsa** [comment]
I think I understand. Hmmm, yeah I was curious about the quantization or compression ratio...I feel like it's still possible to have it grayscale with just a larger image size, im just not sure how, can the ratio be changed? I had been checking out: https://github.com/TibRib/SoundImager 
But this is PNG. JPEG is a much cooler idea.

**Comment by MetrosiderosExcelsa** [comment]
I can do that yup! I just have to run ubuntu off my USB to run it since I couldn't figure out how to run it on windows, might take me a little bit. I will upload them here shortly.

**Comment by MetrosiderosExcelsa** [comment]
Oh I just realized there is already a BMP in their repository, the classic.wav, which is 1.8MB. 
When I run the same classic.wav through JAEG, the output is 272KB. The difference must be the compression ratio I think, though there has to be some way to alter a JPEG compression ratio

**Comment by Eiim** [comment]
Yes, the "Quality" slider on the JAEG website affects the compression ratio. It is interesting that the JAEG result is 4x larger in dimensions than their BMP. It's no surprise that the BMP is larger in size because it's also an uncompressed format.

**Comment by MetrosiderosExcelsa** [comment]
Maybe this is the issue then, at least on my end? The quality slider does not change the output size of the image?  The output always remains the same size, either left or right on the quality slider

**Comment by Eiim** [comment]
Yep, that's a problem. Fixed.

**Comment by Eiim** [comment]
1. There's probably some way to pass a blob to an <audio> tag, but I don't know what it is. I might look into it later.
2. That would just require a bit more math to implement on the output side to calculate a width and a height. Although the input image should be able to be any dimensions.

**Comment by MetrosiderosExcelsa** [comment]
That'd be super sweet.  
For instance I can crop the image and load it back in which is super awesome, but I was imagining a scenario where less cropping had to occur, so less data would be lost, if it was 4:3. Though some cameras can do 1:1, but that's also at an extra loss of information on top.

**Comment by MetrosiderosExcelsa** [comment]
So here are some interesting tests: https://www.dropbox.com/sh/d801w2ivl6udg1c/AADwWbluAKpXqx6eWdZMkbb1a?dl=0  
I printed a JPEG on paper, then captured it with my camera. I cropped the image to include only the info of the JPEG. 
Cameraout.wav is what I get back straight up. 
Resized.wav , I changed the image size to the original JPEG dimensions. The sound can barely be heard, but it is there.

I'm wondering if there is a way to not have to resize the image to the original dimensions so it can be played?  
Or to have a input section where you could put in the correct dimensions of the original JPEG.   
Another thing I had thought was to output PNG, but input JPEG?  
:D

**Comment by MetrosiderosExcelsa** [comment]
Actually that probably makes sense why it sounds so bad.... it has double the JPEG compression on it ! Doh! So yes, outputting PNG would actually make sense, then inputting JPEG. But I don't know how to keep all the pixels (2378 x 2384 for my camera) and treat it as the original size.

**Comment by Eiim** [comment]
Hopefully, max quality output should now be pixel-identical to PNG output. But converting from JPEG to audio is highly sensitive to the precise placements of the pixels, especially with regards to any rotation, so I'm a little surprised you got a recognizable result back out of the process at all!

I also was planning to add JPEG-specific metadata to the results to encode sample rate and such, which would prevent PNG output from working as well. In general, the results are not intended to be printed, but to be used simply as digital files. If you want to encode something that can be printed and scanned, you'd want some kind of highly dense 2D barcode (like a QR code), which this is not intended to be.

**Comment by MetrosiderosExcelsa** [comment]
Oh yes you are correct, I just ran the classic.wav from earlier, and the output is a 1.26MB JPEG on the highest quality compression vs the BMP output of 1.83MB, so more or less the same size, but missing a little bit.  
I actually think the information is there, like if you listen to cameraout.wav it just sounds like it is oscillating, the whole sound was stretched out from 16 seconds to 2 minutes.....which makes me think that there should be a way to represent "speed" per row of pixels or something.  
For resized.wav, I think the buzzing must be the JPEG compression artifacts, the slight loss from the first compression, then my cameras JPEG compression on top of it. 

I think by increasing the images output size at the beginning by adding extra information, like increasing 1 pixel to be a 10 pixel clump instead for instance, would allow less "stretch" factor, then the camera wouldn't have to strain to resolve. Packing more information into the same area, even if its extra information of the same information.  
Then all you'd have to do is input the original image dimensions when loading the image back in, after cropping the image (if 1:)

**Comment by Eiim** [comment]
You're more than welcome to upscale the image, but I don't see how that will help you. And yes, since it's set to 1 pixel = 1/44100 of a second, different dimensions will affect the length of the result. You can downscale your camera's cropped image to the original dimensions to help.

I'm confused by this section:
> ...then the camera wouldn't have to strain to resolve. Packing more information into the same area, even if its extra information of the same information.
Adding more information to the same area will only make it _harder_ to resolve. And again, this really isn't intended to be printed and photographed to recover the information: I'd need to add alignment sections and other such features to make that happen, and I'm just not interested in doing that.

**Comment by MetrosiderosExcelsa** [comment]
Oh shoot you're right haha, what am I thinking, it would be harder to resolve. I think I've confused myself.  
If 1 pixel = 1/44100, I'm wondering how would I take the raw cameraout.wav to get it back to 16 seconds? I can hear the oscillations, and they sound sonically not too terrible. As opposed to having to change the image dimensions to the original image dimensions?

**Comment by MetrosiderosExcelsa** [comment]
Yeah I had tried last night to speed it up, I think it was 700%, so 7x?  It didn't sound good at all, not compared to resizing to the original dimensions.  I wonder about doubling the dimension of the original. No idea. I'm going to mess around and see..

**Comment by MetrosiderosExcelsa** [comment]
+ When I zoom into resized.wav there are perfectly spaced peaks: https://imgur.com/a/2tfqGsa 
Very intruiging

**Comment by MetrosiderosExcelsa** [comment]
I tried: https://redketchup.io/image-resizer
And your program allows me to load PNG! 
Output:  
https://www.dropbox.com/s/424jx9mnq9g0r9n/Cameraout%20PNG.wav?dl=0
So a better than the original, but still terrible

**Comment by Eiim** [comment]
The line here:
```
imageConversion.canvastoFile(canvas, quality, "image/jpeg").then(file => {
```

is what makes it a JPEG. If you change that to "image/png", it should work. You can also change the file extension on the line a little lower down, or just change it manually when you download the file. I highly doubt that any of that will matter though, as the main loss will be from the photographing process, as pixels won't align and downscale properly, and even very slight rotation or distortion of the paper may cause significant issues.

**Comment by MetrosiderosExcelsa** [comment]
Cool, that was surprisingly much easier than I had anticipated....yes so a BMP output of classic.wav is 1.48MB, while a JPEG is 1.26MB. I wonder if TIFF will work too....will try some more experiments.  
I think the distortion would be more of a feature than a bug haha, but yeah rotation seems to be a major issue.....I was thinking one way to remedy this would be to make each pixel row 5 times the height (some arbitrary number) and then somehow read back the averaged pixels across the row, if you know what I mean?  Because if there was a slight rotation, then there would be extra room to wiggle

**Comment by Eiim** [comment]
The proper way to correct for rotation (and distortion, if you're fancy) is by using some relatively basic CV to virtually place a grid of points over the image and find the value at each point, possibly with interpolation, but that's well outside the scope of this project. There's really not much to be done from an encoding perspective here without entirely changing the encoding to something that is designed to be amenable to scanning, as there's just such a high density of information. Which does itself sound like an interesting project! I don't know that I've ever seen what would effectively be analog barcodes before. But it's not one I'm interested in right now.

**Comment by MetrosiderosExcelsa** [comment]
That makes sense. Fair enough, and I appreciate the help. 
I'll link here today one more test with the printed BMP image just to see if it sounds better than the original printed JPEG. I think even with rotation distortion could be super neat. Cheers!

**Comment by MetrosiderosExcelsa** [comment]
Audible, but yeah distorted: https://www.dropbox.com/s/51icthmhtc6ke42/classictest.wav?dl=0

**Comment by MetrosiderosExcelsa** [comment]
And....im back lol.  
I was messing with it a bit more and realized that you can also change the sample rate to 96000 instead of resizing the image to keep the info. 
I was also looking at the differences between the printed image and the digital one, and thought:
Would there be a way to have less than 255 shades of grey? (the movie)
I was thinking 2-bit grayscale, even binary for fun.   
I tried changing the 255's but that just made it transparent.  Could there be a function where the user could change the bitrate?

**Comment by Eiim** [comment]
I suppose you could quantize it to less than 256 colors, but why?

The line you'd want to change is `darkness = ((audioarr[i]/max)+1)*128;`, by the way.

**Comment by Eiim** [comment]
An aspect ration option has now been added.

**Comment by MetrosiderosExcelsa** [comment]
Excellent! 
And yes I realized quantizing to less than 256 colors doesn't make sense in this case, was just thinking maybe the camera would pick up the image better if it had more contrast and was less prone to blur/was binary.  But the main issue for quality sound retrieval seems to be actual rotation of the pixels as you've said.  
I think there is an audio playing blob here: https://github.com/jantepya/Image-Sounder  but I wouldn't know how to incorporate it in JAEG.

**Comment by MetrosiderosExcelsa** [comment]
I was looking at: https://github.com/phamquiluan/jdeskew  
I wonder if something like this with a black bar going right through the center of the image would work for an analog input.  
Instead of opencv, or borders.

**Comment by MetrosiderosExcelsa** [comment]
I found this: https://github.com/phamquiluan/jdeskew 
Maybe if there were a line right through the middle, this would work at least for rotation
